[project]
name = "mcp-interminal"
version = "1.0.4"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["mcp[cli]", "paramiko"]

[project.optional-dependencies]
pty = ["pywinpty"]
ansi = ["pyte"]

[project.scripts]
interminal = "mcp_server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
  "/.venv",
  "/dist",
  "/__pycache__"
]

[tool.hatch.build.targets.wheel]
include = [
  "/*.py"
]
